#! /usr/bin/perl

open( INP, "< build.h" ) || die( "Could not read build.h: " );
for( $n="0" ; $n=="0" ; ) {
   $_ = <INP>;
   ($n) = ( m/build \D*(\d+)/ );
   }
close( INP );

$git_tag = `git tag | tail -1`;
chop($git_tag);

$n++;

open( OUT, "> build.h" ) || die( "Could not write build.h: " );

@now = localtime();
$yr = $now[5]+1900;
$mo = $now[4]+1;
$dy = $now[3];

$str = sprintf("%d/%2.2d/%2.2d",$yr,$mo,$dy);
$git = `git tag -l`;
$git =~ s/\s*$//;

print OUT <<EOF ;
#ifndef BUILD_H
#define BUILD_H

static char *verstr = "build $n ($str)" ;
static char *gitver = "$git_tag" ;

#endif /* BUILD_H */
EOF
